# This is a basic algorithm to pre-compute 67 code for each value of a u8.
# It's currently run as a build step and shouldn't be modified.

from datetime import datetime

# seeding the ruleset
rules: list[str | None] = [None] * 256
rules[6] = "66"
rules[7] = "67"

# functions for calculating results of operations
def tryAdd(a: tuple[int, str], b: tuple[int, str]) -> tuple[int,str]:
    res = (a[0] + b[0]) % 256
    lit = a[1] + b[1] + "7666"
    return res,lit

def trySubtract(a: tuple[int, str], b: tuple[int, str]) -> tuple[int,str]:
    res = (a[0] - b[0]) % 256
    lit = a[1] + b[1] + "7667"
    return res,lit

def tryMultiply(a: tuple[int, str], b: tuple[int, str]) -> tuple[int,str]:
    res = (a[0] * b[0]) % 256
    lit = a[1] + b[1] + "7676"
    return res,lit

# conditional updating
def tryUpdate(a: tuple[int, str]):
    global rules
    i, v = a
    if rules[i] is None:
        rules[i] = v
        return
    rules[i] = min(v, rules[i], key=len)

# Updating by finding all values we can create and choosing the shortest program
def updateStep():
    base = rules[:]
    for a in enumerate(base):
        if a[1] is None: continue
        for b in enumerate(base):
            if b[1] is None: continue
            tryUpdate(tryAdd(a, b))
            tryUpdate(trySubtract(a, b))
            tryUpdate(tryMultiply(a, b))

# Outputting the result as a valid `.zig` file :)
def outputRules(file=None):
    global rules
    # editing disclaimer
    print("// This file was autogenerated at build time.", file=file)
    print("// Edits in this file will not be reflected in the executable or in",
          file=file)
    print("// future builds.", file=file)
    print("// generated at", datetime.now().isoformat(), file=file)

    # actual zig stuff
    print("public const RuleShorthand = [_][]const u8{", file=file)
    for rule in rules:
        print(f"    \"{rule}\",", file=file)
    print("};", file=file)


# Actually creating the ruleset :)

while None in rules:
    updateStep()

with open("src/ruleset.zig", "w") as f:
    outputRules(f)
